import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "Sabrhea's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
